

trigger:
  branches:
    include:
    - master
    - main
    - develop

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
      - master
      - main
      - develop
    always: true

pool:
  name: 'Default'

steps:
- checkout: self




- task: Xcode@5
  displayName: 'iOS Xcode build'
  inputs:
    actions: 'clean build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: '**/*.xcodeproj'
    scheme: 'AzureWithYml19Mart'
    xcodeVersion: 'default'
    packageApp: true
    signingOption: 'false'
   



#- task: ms-vsclient.app-store.app-store-release.AppStoreRelease@1
#  displayName: 'Publish to the App Store TestFlight track'
#  inputs:
#    serviceEndpoint: 'App Store Connect'
#    appIdentifier: com.ergene.AzureOrnek
#    shouldSkipWaitingForProcessing: true
#    shouldSkipSubmission: true
#
