
variables:
  buildScheme: 'AzureWithYml19Mart'  # Uygulamanızın Xcode scheme'ini buraya girin.
  buildSdk: 'iphoneos'
  buildConfiguration: 'Release'
  workspacePath: '**/*.xcodeproj'  # Eğer bir workspace kullanıyorsanız, burayı ayarlayın.
  xcodeVer: 'default'  # Seçenekler: 8, 9, 10, 11, 12, default, specifyPath

trigger:
  branches:
    include:
    - master
    - main
    - develop

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
      - master
      - main
      - develop
    always: true

pool:
  name: 'Default'

steps:
- checkout: self



- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: $(buildScheme)
    sdk: $(buildSdk)
    configuration: $(buildConfiguration)
    xcWorkspacePath: $(workspacePath)
    xcodeVersion: $(xcodeVer)

- task: Xcode@5
  inputs:
    actions: 'archive'
    scheme: $(buildScheme)
    sdk: $(buildSdk)
    configuration: $(buildConfiguration)
    xcWorkspacePath: $(workspacePath)
    xcodeVersion: $(xcodeVer)
    packageApp: true
    archivePath: '$(Build.ArtifactStagingDirectory)/$(buildScheme).xcarchive'

- task: Xcode@5
  inputs:
    actions: 'export'
    sdk: $(buildSdk)
    xcWorkspacePath: $(workspacePath)
    xcodeVersion: $(xcodeVer)
    exportOptionsPlist: 'path/to/your/exportOptions.plist'
    archivePath: '$(Build.ArtifactStagingDirectory)/$(buildScheme).xcarchive'
    exportPath: '$(Build.ArtifactStagingDirectory)/ipa'
